import type { Plugin } from "vitest/config";

export interface AutoImportOptions {
	imports?: string[];
	dts?: string | boolean;
}

const defaultImports = [
	"describe",
	"it",
	"test",
	"expect",
	"beforeAll",
	"beforeEach",
	"afterAll",
	"afterEach",
	"vi",
];

export function vitestAutoImport(options: AutoImportOptions = {}): Plugin {
	const imports = options.imports || defaultImports;
	const dtsPath = options.dts === true ? "vitest-auto-imports.d.ts" : options.dts;

	return {
		name: "vitest-plugin-auto-import",
		config() {
			return {
				test: {
					globals: true,
				},
			};
		},
		async configResolved(config) {
			if (dtsPath && config.command === "build") {
				await generateDts(dtsPath, imports);
			}
		},
	};
}

async function generateDts(path: string, imports: string[]): Promise<void> {
	const content = `// Auto-generated by @wrikka/vitest-plugin-auto-import
import type { ${imports.join(", ")} } from 'vitest'

declare global {
  ${imports.map((name) => `const ${name}: typeof import('vitest')['${name}']`).join("\n  ")}
}

export {}
`;

	const isBrowser = typeof (globalThis as unknown as { window?: unknown }).window !== "undefined";
	if (!isBrowser) {
		const fs = await import("node:fs");
		fs.writeFileSync(path, content);
	}
}

export default vitestAutoImport;
